# Generated by Django 5.1.7 on 2025-03-20 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_total_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('kg', 'Kilogramm'), ('tonna', 'Tonna'), ('metr', 'Metr'), ('dona', 'Dona'), ('litr', 'Litr'), ('oram', 'O‘ram'), ('qop', 'Qop'), ('quti', 'Quti'), ('gramm', 'Gramm')], default='dona', max_length=10, verbose_name='O‘lchov birligi'),
        ),
    ]
