# Generated by Django 5.1.7 on 2025-03-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.FloatField(default=0.0, verbose_name='Miqdor'),
        ),
    ]
